name: Push and Deploy Serverless function
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v2
        with:
          token: ${{ secrets.TOKEN }}
          #bucket: ${{ secrets.BUCKET }}
          #accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          #secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          function_id: "d4e5pgmrqqrr0hvu9pvu"
          runtime: "golang121"
          memory: "128"
          entrypoint: "index.Handler"
          environment: DEBUG=True,COUNT=1
          source: "."
